update the instruction for pinging an IPv4 address
openthread/ot-docs pull request #103
Opened 2022-10-12 08:48 UTC by xuyirio

This PR updates the instruction for pinging an IPv4 address. After [updating the default NAT64 service to be openthread](https://github.com/openthread/ot-br-posix/pull/1539), users will be able to ping an IPv4 address directly.

2022-10-24 06:30 UTC, erjiaqing commented on site/en/guides/border-router/docker/test-connectivity.md
> +2.  To get a translated IPv4 address, use a website like
I think we don't need this anymore.

2022-10-24 06:42 UTC, erjiaqing approved these changes

2022-10-24 06:42 UTC, xuyirio commented on site/en/guides/border-router/docker/test-connectivity.md
> +2.  To get a translated IPv4 address, use a website like
Done.

2022-10-24 16:28 UTC, Vyrastas requested changes
Looks good, just a few minor copyedits

2022-10-24 16:28 UTC, Vyrastas commented on site/en/guides/border-router/docker/test-connectivity.md
> +Thread network.
in the Thread network

2022-10-24 16:28 UTC, Vyrastas commented on site/en/guides/border-router/docker/test-connectivity.md
> +1.  To view the NAT64 prefix in Thread network
colon at the end of this, add in "the"

To view the NAT64 prefix in the Thread network:

2022-10-24 16:28 UTC, Vyrastas commented on site/en/guides/border-router/docker/test-connectivity.md
> +    test its internet connectivity.
colon at the end

test its internet connectivity:

2022-10-25 02:11 UTC, xuyirio commented on site/en/guides/border-router/docker/test-connectivity.md
> +Thread network.
Done. Thanks!

2022-10-25 15:29 UTC, Vyrastas approved these changes

2022-10-25 17:17 UTC, jwhui approved these changes

2022-10-25 17:18 UTC, merged