[guides] migrate border-router guides
openthread/ot-docs pull request #13
Opened 2021-05-04 19:24 UTC by gavinmcgovern

2021-05-05 22:10 UTC, Vyrastas commented on site/en/guides/border-router/docker/cleanup-and-basics.md
> +Docker](../../../../guides/border-router/docker/run.md) and [Test
These relative links should move up only 3 directories, not 4.  Anything in the /docker directory should be 3

2021-05-05 22:10 UTC, Vyrastas commented on site/en/guides/border-router/raspberry-pi.md
> +1.  [Build and install OTBR](../../../guides/border-router/build/index.md).
The local links for pages in the border-router/ directory should only need to go up 2, not 3

2021-05-12 17:20 UTC, Vyrastas requested changes

2021-05-12 17:20 UTC, Vyrastas commented on site/en/guides/border-router/tools.md
> +pskc {&lt;commissioner-credential&gt; &lt;extpanid&gt; &lt;network-name&gt;}
Each parameter should be a replaceable variable

pskc {commissioner-credential} {extpanid} {network-name}

2021-05-12 17:20 UTC, Vyrastas commented on site/en/guides/border-router/tools.md
> +steering-data {[length] &lt;joiner-id&gt;}
Let's try this

steering-data [{length}] {joiner-id}

2021-05-12 17:20 UTC, Vyrastas commented on site/en/guides/border-router/serial-cables.md
> +
Can you add a <br /> here, it'll help on DevSite

2021-05-12 17:20 UTC, Vyrastas commented on site/en/guides/border-router/docker/test-connectivity.md
> +    ```64:ff9b::acd9:a46e```
Format this like the one in the step below

```
64:ff9b::acd9:a46e
```

2021-05-18 17:01 UTC, Vyrastas commented on site/en/guides/border-router/tools.md
> +pskc {&lt;commissioner-credential&gt; &lt;extpanid&gt; &lt;network-name&gt;}
Remove the &lt; and &gt; it should just be

pskc {commissioner-credential} {extpanid} {network-name}

2021-05-18 17:02 UTC, Vyrastas commented on site/en/guides/border-router/tools.md
> +steering-data {[length] &lt;joiner-id&gt;}
This doesn't appear to have been done

steering-data [{length}] {joiner-id}

2021-05-18 17:04 UTC, Vyrastas approved these changes

2021-05-18 17:04 UTC, Vyrastas commented
Please double-check the Copybara import results but I think we're good to go here.

2021-05-18 22:15 UTC, jwhui approved these changes

2021-05-18 22:15 UTC, merged