[docs] CoAPS Concepts Guide
openthread/ot-docs pull request #154
Opened 2024-02-16 23:16 UTC by jrhodie

2024-02-16 23:35 UTC, abtink reviewed
Looks good. Thanks. 

One suggestion about "CoAPS" use.

2024-02-16 23:35 UTC, abtink commented on site/en/reference/cli/concepts/coaps.md
> +OpenThread offers both CoAPS server and client functionality, enabling devices
CoAP is well-known abbreviation. But "CoAPS" is not. Suggest using `secure CoAP` instead of `CoAPS` in the docs here and below?

2024-02-16 23:35 UTC, abtink commented on site/en/reference/cli/concepts/coaps.md
> +             ```
Aligne "````"?

2024-02-16 23:35 UTC, abtink commented on site/en/reference/cli/concepts/coaps.md
> +            ```
Same here?

2024-02-17 00:06 UTC, jrhodie commented
@abtink -  Thanks, I incorporated your comments.

2024-02-17 18:15 UTC, abtink approved these changes
Thanks. 👍

2024-02-20 16:29 UTC, Vyrastas requested changes
Looks good, just a couple of things

2024-02-20 16:29 UTC, Vyrastas commented on site/en/reference/cli/concepts/coaps.md
> +This guide provides basic tasks that use some of the more common Secure CoAP (or `coaps`) commands.
```suggestion
This guide provides basic tasks that use some of the more common Secure CoAP (`coaps`) commands.
```

2024-02-20 16:29 UTC, Vyrastas commented on site/en/reference/cli/concepts/coaps.md
> +   parameter when the `type` is either `con` or `non-con`."
```suggestion
   parameter when the `type` is either `con` or `non-con`.
```

2024-02-20 18:58 UTC, Vyrastas approved these changes

2024-02-20 20:44 UTC, merged