[Docs] Added warning to Operational Datasets Concepts Guide
openthread/ot-docs pull request #159
Opened 2024-04-15 19:34 UTC by jrhodie

2024-04-15 19:54 UTC, Vyrastas requested changes

2024-04-15 19:54 UTC, Vyrastas commented on site/en/reference/cli/concepts/dataset.md
> +The CLI commands to write/change the Active and Pending Operational Datasets may allow setting invalid parameters, or
Don't use slashes, instead do "write or change".  Update the other instance below.

2024-04-15 19:54 UTC, Vyrastas commented on site/en/reference/cli/concepts/dataset.md
> +- For testing (not applicable to production devices).
Please use * instead of - for consistency with the other lists on this page

2024-04-15 19:54 UTC, Vyrastas commented on site/en/reference/cli/concepts/dataset.md
> +In production Thread networks, the correct method to write/change Operational Datasets is via a
I know this came from the README but let's use "through" instead of "via" to align with the website style

2024-04-15 20:43 UTC, Vyrastas approved these changes

2024-04-16 16:25 UTC, abtink approved these changes
👍

2024-04-16 17:03 UTC, jwhui approved these changes

2024-04-16 17:03 UTC, merged