Disclaimer about router terminology on node-roles-and-types.md
openthread/ot-docs pull request #160
Opened 2024-04-24 19:01 UTC by rochaferraz

Routers are now officially named "Thread Mesh Extenders" on all consumer facing comms. Adding this information here.

Q: should we update *all* documentation to reflect the name change or can we still use "router" in engineering docs and primers?

2024-06-07 22:53 UTC, Vyrastas commented
Sorry, I missed this.  @jwhui is this a change we should make in the OpenThread docs?

2024-06-10 19:59 UTC, jwhui commented
> Sorry, I missed this. @jwhui is this a change we should make in the OpenThread docs?

Yes, we should put something to this effect. "Mesh Extenders" is the name Thread Group recommends for consumer-facing documentation. But "Routers" is still used by the Thread Specification.

2024-06-13 22:53 UTC, Vyrastas commented
Yeah I would just change it a few places for now, these docs are not really for consumers.  I haven't looked at the Primer material in a while, I'll have to see other places where it makes sense to change and also mention Mesh Extenders.

2025-07-13 15:03 UTC, EskoDijk commented
@Vyrastas Currently the term "Router" is still used in Thread 1.4.x specifications. Change of the term is pending for a future spec update, but is not the highest priority.

2025-08-13 06:12 UTC, jwhui commented
/gemini review

2025-08-13 12:46 UTC, EskoDijk commented
Just a review comment on this: per https://threadgroup.atlassian.net/browse/SPEC-1288 , the term "Router" would be updated to "Mesh Extender" (and not "Thread Mesh Extender").
The term "Thread Router" would be updated to "Thread Mesh Extender".  Should we follow the same logic here?

2025-08-13 17:28 UTC, Vyrastas requested changes
Can approve once the AI/bot comments are addressed

2025-08-20 13:22 UTC, EskoDijk commented
> Can approve once the AI/bot comments are addressed

And my comment, hopefully! Although phrased as a question, I proposed a change in the terminology, to keep consistency. I.e. use the term "Mesh Extender" instead of "Router".

2026-07-28 20:51 UTC, jwhui commented
Closing stale PR.

2026-07-28 20:51 UTC, closed without merging