[otns] Update OTNS codelab to OTNS2.
openthread/ot-docs pull request #167
Opened 2024-09-24 13:55 UTC by EskoDijk

This updates the OTNS codelab to use the new OTNS2 simulator, which is currently not yet in the OpenThread project Github. The PR for OTNS2 is currently [here](https://github.com/openthread/ot-ns/pull/530).

It should be merged/accepted only after we have accepted OTNS2. This could be considered a draft PR, until that time. Some verification / fixes and checking required time may still be needed.

2024-09-25 17:25 UTC, Vyrastas requested changes
This all looks great, thanks for doing the update!  A few comments

2024-09-25 17:25 UTC, Vyrastas commented on site/en/codelabs/openthread-network-simulator/img/00_otns_web.png
Can you also in this PR delete any old images that you've replaced?  No need to keep them.

2024-09-25 17:25 UTC, Vyrastas commented on site/en/codelabs/openthread-network-simulator/index.lab.md
> +In case of other errors, a [Github issue](https://github.com/openthread/ot-ns/issues) can be created.
```suggestion
In case of other errors, a [GitHub issue](https://github.com/openthread/ot-ns/issues) can be created.
```

2024-09-25 17:25 UTC, Vyrastas commented on site/en/codelabs/openthread-network-simulator/index.lab.md
>  enabled in your browser. Please refer to**
Can you clean up this paragraph while you're at it, please.  Should just be a single bold around the whole thing, and needs a space between "to" and the link.

2024-09-25 17:25 UTC, Vyrastas commented on site/en/codelabs/openthread-network-simulator/img/00_otns_web.png
Can you add a black border around each image?  They way they are cut off is inconsistent when viewing it on the website (solid black line on one side, or on two).

2024-09-25 17:25 UTC, Vyrastas commented on site/en/codelabs/openthread-network-simulator/index.lab.md
> +The absolute simulation time in microseconds is shown on the left. The hh:mm:ss timestamp shows the OpenThread node's
```suggestion
The absolute simulation time in microseconds is shown on the left. The `hh:mm:ss` timestamp shows the OpenThread node's 
```

2024-09-25 17:25 UTC, Vyrastas commented on site/en/codelabs/openthread-network-simulator/index.lab.md
> +properly decrypt when loaded.
Menus and buttons should be in bold.

```suggestion
To configure the decryption key, select in the menu **Edit -> Preferences**. Then in the preferences window, select 
**Protocols -> IEEE 802.15.4**. Click the **Edit...** button next to "Decryption Keys". Click **+** to create a new entry 
and enter the key `00112233445566778899aabbccddeeff` (32 characters) and select "Thread hash" in the "Key hash" field. 
The "Decryption key index" can be left to `0`. Then click **OK**, and **OK** again. Now the OTNS PCAP file should 
properly decrypt when loaded. 
```

2024-09-26 09:54 UTC, EskoDijk commented on site/en/codelabs/openthread-network-simulator/img/00_otns_web.png
Yes, good idea.

2024-09-26 09:56 UTC, EskoDijk commented on site/en/codelabs/openthread-network-simulator/img/00_otns_web.png
Ok, so that should be black border of 1 pixel wide? I can do that.

2024-09-26 20:34 UTC, Vyrastas commented on site/en/codelabs/openthread-network-simulator/img/00_otns_web.png
Yeah 1 pixel is fine, just something to make them stand out better

2024-09-28 11:57 UTC, EskoDijk commented
@Vyrastas I've now made an update based on your review. Also added one more paragraph about timestamps correlation.

For merging this update we would probably have to wait until the OTNS2 PR is done (https://github.com/openthread/ot-ns/pull/530) ?

2024-10-02 03:56 UTC, Vyrastas requested changes
Thanks for making all the image updates @EskoDijk !

Just some copyedit nits, otherwise looks good to me.  And yes we should wait for the other PR to be in before submitting this.

Have you had anyone else try out this updated version of the codelab?  I only reviewed from an editorial standpoint, I did not verify that it works as written.

2024-10-02 03:56 UTC, Vyrastas commented on site/en/codelabs/openthread-network-simulator/index.lab.md
> +### Bootstrap and Install
```suggestion
### Bootstrap and install
```

2024-10-02 03:56 UTC, Vyrastas commented on site/en/codelabs/openthread-network-simulator/index.lab.md
> +## Run OTNS For the First Time
```suggestion
## Run OTNS for the first time
```

2024-10-02 03:56 UTC, Vyrastas commented on site/en/codelabs/openthread-network-simulator/index.lab.md
> +Also click the FED, MED, SSED and BR buttons on the Action Bar to create these other types
```suggestion
Also click the FED, MED, SSED, and BR buttons on the Action Bar to create these other types
```

2024-10-02 03:56 UTC, Vyrastas commented on site/en/codelabs/openthread-network-simulator/index.lab.md
> +> Blue indicates it is not a Parent/Child link, but other: for example Router-to-Router.
```suggestion
> Blue indicates it is not a Parent/Child link, but something else, such as a Router-to-Router link.
```

2024-10-02 03:56 UTC, Vyrastas commented on site/en/codelabs/openthread-network-simulator/index.lab.md
> +## Viewing Node Logs and Packet Captures
```suggestion
## Viewing node logs and packet captures
```

2024-10-02 03:56 UTC, Vyrastas commented on site/en/codelabs/openthread-network-simulator/index.lab.md
> +### Wireshark Packet Captures
```suggestion
### Wireshark packet captures
```

2024-10-02 07:14 UTC, EskoDijk commented
Thanks, updated with the suggestions now.

> Have you had anyone else try out this updated version of the codelab? I only reviewed from an editorial standpoint, I did not verify that it works as written.

No, not yet. I could do a first pass myself to spot any issues, using [this rendering](https://github.com/EskoDijk/ot-docs/blob/pr-otns2-codelab/site/en/codelabs/openthread-network-simulator/index.lab.md). If we know any testing candidates let me know :) 

What I notice there is that some screenshots (ones that are wider) need to be enlarged, preferably to fill the entire width of the text-box/content-area in some cases.  

As a test, I added a commit using `width="95%"` (or similar) to set the width relative to the column width , for some pictures. The text is now much better readable. (In the real website, the column is slightly narrower though but comparable.)
So if that looks ok I'll adjust all the images to the right width.  For the wider screenshots, they need to fill 100% of column width while for the narrower screenshots it should be less.

2024-10-03 17:50 UTC, Vyrastas commented on site/en/codelabs/openthread-network-simulator/index.lab.md
> +<img src="img/12_7n_del_br.png" alt="Border Router node 9 is deleted" width="642.12" />
I would make the width here consistent with the others, otherwise they are all fine

2024-10-03 17:51 UTC, Vyrastas commented
> As a test, I added a commit using `width="95%"` (or similar) to set the width relative to the column width , for some pictures. The text is now much better readable. (In the real website, the column is slightly narrower though but comparable.) So if that looks ok I'll adjust all the images to the right width. For the wider screenshots, they need to fill 100% of column width while for the narrower screenshots it should be less.

Everything looks fine on the openthread.io version (which I can't share externally), except for one image which I flagged (smaller width than the others).  Thanks for doing the extra work to make it look nice!

2025-04-30 21:42 UTC, Vyrastas approved these changes

2025-05-13 14:19 UTC, jwhui approved these changes
Thanks!

2025-05-13 14:20 UTC, merged