[guides] migrate enhanced features
openthread/ot-docs pull request #7
Opened 2021-04-19 21:33 UTC by gavinmcgovern

2021-04-19 23:16 UTC, Vyrastas requested changes

2021-04-19 23:16 UTC, Vyrastas commented on site/en/guides/build/features/jam-detection.md
> +<a href="/guides/images/ot-jam-detection-graph_2x.png"><img src="/guides/images/ot-jam-detection-graph.png" srcset="/guides/images/ot-jam-detection-graph.png 1x, /guides/images/ot-jam-detection-graph
This image isn't loading, I think we need to change the path to be relative to the file

../../images/ot-jam-detection-graph_2x.png

Double-check that it still appears on the DevSite staging with that changed (it should)

If so, you'll have to update /guides/build/commissioning.md too, there's an image at the beginning there that's not loading.

2021-04-20 18:57 UTC, Vyrastas approved these changes

2021-04-20 18:59 UTC, jwhui approved these changes

2021-04-20 18:59 UTC, merged