Change to `openthread/environment` Docker image
openthread/ot-docs pull request #71
Opened 2022-02-01 17:36 UTC by j-noel-longhand

Updated Docker image reference to `openthread/environment` and updated binaries paths to reflect this change.

2022-02-01 18:19 UTC, Vyrastas requested changes

2022-02-01 18:19 UTC, Vyrastas commented on site/en/codelabs/openthread-simulation/index.lab.md
> +~/projects/7314-consolidate_codelab_sim_dockerfile_into_environment_dockerfile/---
Revert the change on this line, looks like something from your local machine

2022-02-01 22:33 UTC, Vyrastas commented on site/en/codelabs/openthread-simulation/index.lab.md
>  id: openthread-simulation
Originally there were 3 dashes at the top of the page.  They might be needed on the DevSite side, can you add them back?

2022-02-01 23:02 UTC, Vyrastas approved these changes

2022-02-02 06:19 UTC, jwhui approved these changes
Thanks! 👍🏼

2022-02-02 06:19 UTC, merged