fix the approach to quiting ot-ctl
openthread/ot-docs pull request #89
Opened 2022-06-22 09:08 UTC by jcdong98

`exit` command is the only way to quit ot-ctl, and it will not lead to termination of ot-daemon.

2022-06-22 09:37 UTC, wgtdkp approved these changes
LGTM 👍

2022-06-24 04:09 UTC, Vyrastas requested changes

2022-06-24 04:09 UTC, Vyrastas commented on site/en/codelabs/openthread-simulation-posix/index.lab.md
> +Quit `ot-ctl` by using either **Ctrl+D** or `exit` command, and on your host machine's command line,
Please make the same changes on the openthread-simulation codelab

https://github.com/openthread/ot-docs/blob/main/site/en/codelabs/openthread-simulation/index.lab.md?plain=1#L892

2022-06-24 04:24 UTC, bukepo approved these changes

2022-06-28 19:17 UTC, Vyrastas approved these changes

2022-06-28 19:17 UTC, Vyrastas commented on site/en/codelabs/openthread-simulation-posix/index.lab.md
> +Quit `ot-ctl` by using either **Ctrl+D** or `exit` command, and on your host machine's command line,
We'll update the other Codelab in a separate PR so this one isn't blocked.

2022-06-28 19:27 UTC, jwhui approved these changes

2022-06-28 19:28 UTC, merged